# Generated by Django 4.1.5 on 2023-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_movie_reviews_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='start',
            field=models.IntegerField(choices=[[1, '*'], [2, '**'], [3, '***'], [4, '****'], [5, '*****']], default=0),
        ),
    ]
