# Generated by Django 4.1.5 on 2023-01-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_review_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='start',
            new_name='stars',
        ),
    ]
